# Generated by Django 3.2.3 on 2021-06-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='log_size',
            new_name='lot_size',
        ),
    ]
